### ISSUE TITLE
Allow the uni admin seeting a "not active from" date for orgs

### ISSUE THREAD

**Issue by viandrea** [openLAMA/Welcome#101]
As an uni admin I want to be able to set a date for orgs, from which on they become inactive and are not counted in the testing stats.

Maybe? Exclusion Start Date

![telegram-cloud-document-4-5967502452407142770](https://user-images.githubusercontent.com/6887897/123806035-dad2db80-d8ee-11eb-8b2a-61cd955d9596.jpg)

**Comment by viandrea** [comment]
@TsvyatkoIvanov @tockata this issue is ready for implementation.

Is it clear enough?

**Comment by TsvyatkoIvanov** [comment]
If they press the "inactive" button, is the date going to be filled automatically with the current date ?
Or is it going to be set manually every time ?

**Comment by viandrea** [comment]
@viandrea check with Anouk if setting an end date e.g. 2030, it would solve her "problem"

**Comment by viandrea** [comment]
Not required any more. Will be solved by user input.
